import Head from 'next/head'
import Link from 'next/link'

export default function Nosotros() {
  return (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Desde Nosotros</h1>
        <Link href="/">Index</Link>
    </div>
  )
}
